### ISSUE TITLE
No module libs.lib

### ISSUE THREAD

**Issue by thanasissdr** [tzutalin/labelImg#164]
When I try to run labelImg (MacOS High Sierra / python 2.7 / pip) there is an error "No module libs.lib". Does anyone know how to solve this?

**Comment by tzutalin** [comment]
what are your steps?

**Comment by tzutalin** [comment]
It seems you can't load libs/lib.py

**Comment by sakaridis** [comment]
@thanasissdr I had the same issue (Debian, python 2.7, pip). More specifically, after

`pip install labelImg; pip install lxml`

I tried to run labelImg from my home directory and got the same error.
The cause of this problem is related to the `PYTHONPATH` environment variable. I'm not very experienced on these topics, but apparently when some of the labelImg scripts attempts to import from libs.lib, it is not able to find this module anywhere in the Python search path.

The work-around that did the trick for me was to:
1) augment `PYTHONPATH` with pwd and directory where labelImg has been installed:
`export PYTHONPATH=".:<Path A>/labelImg:$PYTHONPATH"`
2) run labelImg from the parent directory of the labelImg directory:
`cd <Path A>; labelImg`

`<Path A>` most probably ends with something like `python2.7/site-packages`

**Comment by tzutalin** [comment]
@sakaridis and @thanasissdr 
  Yes, it's an issue. I will fix it.

**Comment by tzutalin** [comment]
Fix it https://github.com/tzutalin/labelImg/commit/d8e961126a32ce582b0dff6407e85b52193ac69a
I will release to pypi later
