### ISSUE TITLE
Please add '.tiff' and '.tif' support when opening a directory

### ISSUE THREAD

**Issue by MouvementMondial** [tzutalin/labelImg#174]
Please change line 1013 in labelImg.py to 
extensions = ['.jpeg', '.jpg', '.png', '.bmp','.tiff','.tif']

Thank you for providing your code!
Kind regards,
mouvementmondial

**Comment by Pavlov228** [comment]
This change in extenstions line doesn't allow to label .tif images anyway. If you try to open image - program doesn't see images. If you try to open folder with .tif images error appears "Error opening file: Make sure ... is a valid image file".

**Comment by cjermain** [comment]
@Pavlov228, TIFF files are supported with Python 2.7 and Qt 4.8, since labelImg relies on `QImageReader` to read the images. `QImageReader` has support for TIFF in [Qt 4.8](http://doc.qt.io/archives/qt-4.8/qimagereader.html#supportedImageFormats), but not in [Qt 5.x](http://doc.qt.io/qt-5/qimagereader.html#supportedImageFormats).

https://github.com/tzutalin/labelImg/blob/dec4885e294549b7655826abe404a0f317b60a93/labelImg.py#L1188

Using the above dependencies will allow TIFF files to be read, but you also need to include the change from @MouvementMondial to add `.tiff` and `.tif` to the extension list. With both of these, I can confirm that labelImg processes TIFFs as expected.

**Comment by vdalv** [comment]
I believe this issue has been resolved. Lmk if that's not the case.

Thanks,

-Vlad

**Comment by ankitom** [comment]
Hi, 
Thanks for this package. Though .tiff files opening, only first image of a tiff file can be labelled, Let's say there are 10 images in a single tiff file, how to label the remaining 9??
