### ISSUE TITLE
PyQt5 and python 2.7

### ISSUE THREAD

**Issue by YangBain** [tzutalin/labelImg#216]
<!--
    Please provide as much as detail and example as you can.
    You can add screenshots if appropriate
---------------------
How to use python 2.7 (anconda) +PyQt5 install labelImg? Thank you very much.

- **OS:**
- **PyQt version:**

**Comment by RodolfoFerro** [comment]
What OS are you using?

**Comment by YangBain** [comment]
I use Linux system. Thank you very much.

**Comment by RodolfoFerro** [comment]
I think that you need to build Qt5 for Python 2.7 in your OS. I now that there's a version of that for Windows (https://github.com/pyqt/python-qt5) but for Linux the solution many times has to be building from source. Some useful links to do so are these:
* https://askubuntu.com/questions/662595/best-way-to-install-pyqt5-for-python-2-7-on-ubuntu-14-04 
* https://plashless.wordpress.com/2014/03/26/building-pyqt5-for-python2-7-on-a-clean-ubuntu-13-10-build-machine/

After building Qt5, you should be able to continue with the usual instructions using `make qt5py3` (if you check the Makefile it doesn't specify the Python version for that instruction). If that doesn't work, instead of using the Makefile you might need to change the instruction to specify that you're using Python 2.7:
```bash
# After installing qt5 for python 2.7
sudo pip install lxml

# Using the Makefile
make qt5py3

# If that doesn't work, specify python version
pyrcc5 -py2 -o resources.py resources.qrc

python labelImg.py
python labelImg.py [IMAGE_PATH] [PRE-DEFINED CLASS FILE]
```

Let us know if it works!

**Comment by YangBain** [comment]
In my window system. I successfully installed it. Thank you very much.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
