### ISSUE TITLE
possibility of displaying 2 images side by side

### ISSUE THREAD

**Issue by priyam1994** [tzutalin/labelImg#217]
In my case, I want to label 2 modalities simultaneously. For example, if I have -

└───RGB
    │   rgb_image1.png
    │   rgb_image2.png
└─── DEPTH
    │  depth_image1.png
    │  depth_image2.png

I wish to see both rgb_image1.png and depth_image1.png on the canvas, label the RGB image and save the same annotations for both images as xml format. How would you advise me to proceed with this?
   

- **OS:** Ubuntu 16.04
- **PyQt version:** Python 2 QT 4

**Comment by vdalv** [comment]
@priyam1994 You can write a simple script that copies and modifies the xml of rgb_image1.png so that it works for depth_image1.png, and then open two instances of labelImg and look at them.

This is a fairly specific use case, so I don't think this is a feature that we'll be adding in the foreseeable future.
