### ISSUE TITLE
Image height and width zero

### ISSUE THREAD

**Issue by BanuSelinTosun** [tzutalin/labelImg#309]
- **OS:**
- **PyQt version:**

I am using the windows version. It was working very good the first time I used it. Filename was the same with image name, if jpg than filename in the xml was image.jpg; in the second run the .jpg part was dropped. The third run also dropped the image sizes, height and width to zero. I am using the same exact method; and I am not sure why I am observing this problem. Any idea?

**Comment by vdalv** [comment]
This issue has been brought to our attention before (https://github.com/tzutalin/labelImg/issues/160). It's mostly likely because your image file has an extension that doesn't match it's actual format. As @wolczek mentioned in [his PR](https://github.com/tzutalin/labelImg/pull/289): "Scraping images from Google Image Search I noticed that around 2% of files have wrong filename extension, for example .png but internally it's JPEG.
In that case output annotation/size/ width and height are zeros."

**Comment by guias12** [comment]
> I also scraped image from google, and the same problem occurred. After rewriting images the problem is solved, so I want to share my experience and code.
> 
> language: Python 3
> code as below:
> 
> import cv2
> import os
> 
> img_path = 'D:\test'
> all_file = os.listdir(img_path)
> os.chdir(img_path) # very important
> for filename in all_file:
> # print(filename)
> img=cv2.imread(filename)
> cv2.imwrite(filename,img,[int(cv2.IMWRITE_JPEG_QUALITY), 100])

that solved my problem too, but i also made sure to rename all the images so it woul have the .jpg extension.
thank you
